image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements-ci.txt

stages:
  - Static Analysis
  - Testing

pycodestyle:
  stage: Static Analysis
  script:
  - pycodestyle .

pytest:
  stage: Testing
  script:
  - pytest exerciseit/

coverage:
  stage: Testing
  script:
  - pytest --cov=activate