image: "python:3.8"

before_script:
  - python --version
  - pip install -r requirements.txt
  - pip install -r requirements-ci.txt

stages:
  - Static Analysis
  - Testing

pycodestyle:
  stage: Static Analysis
  script:
    - pycodestyle .

pytest:
  stage: Testing
  script:
    - pytest

coverage:
  stage: Testing
  script:
    - pytest --cov
  
