# Generated by Django 3.0.3 on 2020-03-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0004_auto_20200319_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='isPro',
            new_name='is_pro',
        ),
    ]
