# Generated by Django 3.0.3 on 2020-03-19 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_page', '0004_auto_20200319_1312'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exerciseTitle', models.CharField(max_length=200, verbose_name='Tittel på øvelsen')),
                ('exerciseInfo', models.TextField(blank=True, max_length=500, null=True, verbose_name='Informasjon om øvelsen')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('isPublic', models.BooleanField(default=False)),
                ('exerciseHowTo', models.TextField(blank=True, max_length=500, null=True, verbose_name='Utførelse av øvelsen')),
                ('exerciseImage', models.ImageField(blank=True, null=True, upload_to='exercises/', verbose_name='Bilde av øvelsen')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_page.CreatedBy', verbose_name='Laget av')),
            ],
            options={
                'ordering': ['exerciseTitle'],
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscleGroupTitle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Favorisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='favorisations',
            field=models.ManyToManyField(blank=True, through='feed.Favorisation', to=settings.AUTH_USER_MODEL, verbose_name='Favoriseringer'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscleGroup',
            field=models.ManyToManyField(blank=True, to='feed.MuscleGroup', verbose_name='Muskelgrupper'),
        ),
    ]
