# Generated by Django 3.0.3 on 2020-02-25 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscleGroupTitle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exerciseTitle', models.CharField(max_length=200)),
                ('exerciseAuthor', models.CharField(max_length=50, null=True)),
                ('exerciseInfo', models.TextField(blank=True, max_length=500, null=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2020, 2, 25, 22, 50, 54, 710677), editable=False)),
                ('exerciseLikes', models.IntegerField(default=0)),
                ('exerciseRating', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('exerciseHowTo', models.TextField(blank=True, max_length=500, null=True)),
                ('createdByPro', models.BooleanField(default=False)),
                ('exerciseImage', models.ImageField(blank=True, null=True, upload_to='exercises/')),
                ('muscleGroup', models.ManyToManyField(blank=True, to='feed.MuscleGroup')),
            ],
            options={
                'ordering': ['exerciseLikes', 'exerciseRating', 'exerciseTitle'],
            },
        ),
    ]
