# Generated by Django 3.0.3 on 2020-02-25 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='pub_date',
            field=models.DateTimeField(
                default=datetime.datetime(2020, 2, 25, 22, 51, 29, 517579),
                editable=False),
        ),
    ]
