# Generated by Django 3.0.3 on 2020-03-19 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_page', '0002_createdby'),
        ('feed', '0002_remove_exercise_createdbypro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['exerciseTitle']},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exerciseLikes',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exerciseRating',
        ),
        migrations.AddField(
            model_name='exercise',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_page.CreatedBy', verbose_name='Laget av'),
        ),
        migrations.CreateModel(
            name='Favorisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='favorisations',
            field=models.ManyToManyField(blank=True, through='feed.Favorisation', to=settings.AUTH_USER_MODEL, verbose_name='Favoriseringer'),
        ),
    ]
