# Generated by Django 3.0.3 on 2020-03-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20200225_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='createdByPro',
            field=models.BooleanField(
                default=False, verbose_name='Profesjonell'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exerciseAuthor',
            field=models.CharField(
                max_length=50, null=True, verbose_name='Forfatternavn'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exerciseHowTo',
            field=models.TextField(
                blank=True,
                max_length=500,
                null=True, verbose_name='Utførelse av øvelsen'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exerciseImage',
            field=models.ImageField(
                blank=True, null=True,
                upload_to='exercises/', verbose_name='Bilde av øvelsen'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exerciseInfo',
            field=models.TextField(
                blank=True, max_length=500,
                null=True, verbose_name='Informasjon om øvelsen'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exerciseTitle',
            field=models.CharField(max_length=200,
                                   verbose_name='Tittel på øvelsen'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscleGroup',
            field=models.ManyToManyField(
                blank=True, to='feed.MuscleGroup',
                verbose_name='Muskelgrupper'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
