# Generated by Django 3.0.3 on 2020-02-24 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_exercise_musclegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exerciseDescription',
        ),
        migrations.AddField(
            model_name='exercise',
            name='createdByPro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exerciseHowTo',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exerciseImage',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='exercises/'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exerciseInfo',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exerciseLikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exerciseRating',
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=4,
                null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscleGroup',
            field=models.ManyToManyField(blank=True, to='feed.MuscleGroup'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='pub_date',
            field=models.DateTimeField(
                default=datetime.datetime(2020, 2, 24, 12, 29, 44, 974038),
                editable=False),
        ),
    ]
