# Generated by Django 3.0.3 on 2020-02-21 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_exercise_musclegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscleGroup',
            field=models.ManyToManyField(blank=True, to='feed.MuscleGroup'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 18, 34, 14, 278594), verbose_name='date published'),
        ),
    ]
