# Generated by Django 3.0.3 on 2020-03-09 17:55

import datetime

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feed', '0003_auto_20200309_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exerciseImage',
            field=image_cropping.fields.ImageCropField(
                upload_to='exercises/', verbose_name='Bilde av øvelsen'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='pub_date',
            field=models.DateTimeField(
                default=datetime.datetime(2020, 3, 9, 18, 55, 41, 148022),
                editable=False),
        ),
    ]
