# Generated by Django 3.0.3 on 2020-02-21 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20200221_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='pub_date',
            field=models.DateTimeField(
                default=datetime.datetime(2020, 2, 21, 18, 35, 23, 210853),
                verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='musclegroup',
            name='muscleGroupTitle',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
