# Generated by Django 3.0.3 on 2020-03-10 07:35

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feed', '0004_auto_20200309_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='cropping',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exerciseImage',
            field=models.ImageField(
                upload_to='exercises/', verbose_name='Bilde av øvelsen'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='pub_date',
            field=models.DateTimeField(
                default=datetime.datetime(2020, 3, 10, 8, 35, 4, 483668),
                editable=False),
        ),
    ]
