# Generated by Django 3.0.3 on 2020-02-22 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20200221_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 15, 27, 52, 719277), verbose_name='date published'),
        ),
    ]
