# Generated by Django 3.0.3 on 2020-02-24 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20200222_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['exerciseLikes', 'exerciseRating', 'exerciseTitle']},
        ),
        migrations.AddField(
            model_name='exercise',
            name='exerciseAuthor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 24, 22, 2, 2, 967479), editable=False),
        ),
        migrations.AlterField(
            model_name='musclegroup',
            name='muscleGroupTitle',
            field=models.CharField(max_length=200),
        ),
    ]
