# Generated by Django 3.0.3 on 2020-02-22 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20200222_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 16, 34, 7, 628756), verbose_name='date published'),
        ),
    ]
